--to create blip (you can change coordinate, blip, name everything here)
Citizen.CreateThread(function()
    Dealer = AddBlipForCoord(vector3(-545.53, -1803.08, 21.65))
    SetBlipSprite (Dealer, 479)
    SetBlipDisplay(Dealer, 52)
    SetBlipScale  (Dealer, 0.75)
    SetBlipAsShortRange(Dealer, true)
    SetBlipColour(Dealer, 3)
    BeginTextCommandSetBlipName('STRING')
    AddTextComponentSubstringPlayerName('Pizzeria')
    EndTextCommandSetBlipName(Dealer)
end)